## Organizers
[organizers.ethglobal]
name = "ETHGlobal"

[organizers.ethbrasil]
name = "Ethereum Brazil"

[organizers.sporkdao]
name = "Spork DAO"

## Events

[events.ethdenver]
name = "ETHDenver"
start_date = "2023-2-14"
end_date = "2023-3-5"
website = "https://www.ethdenver.com/"
location = "4655 Humboldt St, Denver CO 80216 US"
country = "United States"
city = "Denver"
organizer = "sporkdao"
telegram = "ETHDenver"
twitter = "ethereumdenver"

[events.ethrio]
name = "ETHRio"
start_date = "2023-3-28"
end_date = "2023-3-30"
website = "https://www.ethereumbrasil.com/ethereumrio"
country = "Brazil"
city = "Rio"
organizer = "ethbrasil"

[events.ethglobaltokyo]
name = "ETHGlobal Tokyo"
start_date = "2023-4-14"
end_date = "2023-4-16"
website = "https://tokyo.ethglobal.com/"
country = "Japan"
city = "Tokyo"
organizer = "ethglobal"
twitter = "ethglobal"
